// GENERATED by scripts/import-dataset.mjs — do not edit by hand.
// Source: "Industrial Storage Container Dimensions" by Daniel Rosehill, CC BY 4.0
// https://huggingface.co/datasets/danielrosehill/storage-container-dimensions
// External dimensions in mm, capacities in litres.
import type { BoxType } from '../model/types';

export const DATASET_BOXES: BoxType[] = [
  {
    "id": "euro-600x400x120",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 120,
    "capacityL": 20.5,
    "capacityLowL": 20.8,
    "capacityHighL": 24.3,
    "lidded": false
  },
  {
    "id": "euro-600x400x150",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 150,
    "capacityL": 26.4,
    "capacityLowL": 26.7,
    "capacityHighL": 30.6,
    "lidded": false
  },
  {
    "id": "euro-600x400x170",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 170,
    "capacityL": 30.3,
    "capacityLowL": 30.7,
    "capacityHighL": 34.8,
    "lidded": false
  },
  {
    "id": "euro-600x400x175",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 175,
    "capacityL": 31.2,
    "capacityLowL": 31.7,
    "capacityHighL": 35.9,
    "lidded": false
  },
  {
    "id": "euro-600x400x200",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 200,
    "capacityL": 36.1,
    "capacityLowL": 36.6,
    "capacityHighL": 41.1,
    "lidded": false
  },
  {
    "id": "euro-600x400x220",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 220,
    "capacityL": 40,
    "capacityLowL": 40.6,
    "capacityHighL": 45.3,
    "lidded": false
  },
  {
    "id": "euro-600x400x230",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 230,
    "capacityL": 42,
    "capacityLowL": 42.6,
    "capacityHighL": 47.5,
    "lidded": false
  },
  {
    "id": "euro-600x400x240",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 240,
    "capacityL": 43.9,
    "capacityLowL": 44.5,
    "capacityHighL": 49.6,
    "lidded": false
  },
  {
    "id": "euro-600x400x270",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 270,
    "capacityL": 49.8,
    "capacityLowL": 50.5,
    "capacityHighL": 55.9,
    "lidded": false
  },
  {
    "id": "euro-600x400x280",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 280,
    "capacityL": 51.7,
    "capacityLowL": 52.5,
    "capacityHighL": 58,
    "lidded": false
  },
  {
    "id": "euro-600x400x300",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 300,
    "capacityL": 55.6,
    "capacityLowL": 56.4,
    "capacityHighL": 62.2,
    "lidded": false
  },
  {
    "id": "euro-600x400x310",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 310,
    "capacityL": 57.6,
    "capacityLowL": 58.4,
    "capacityHighL": 64.3,
    "lidded": false
  },
  {
    "id": "euro-600x400x320",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 320,
    "capacityL": 59.6,
    "capacityLowL": 60.4,
    "capacityHighL": 66.4,
    "lidded": false
  },
  {
    "id": "euro-600x400x340",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 340,
    "capacityL": 63.5,
    "capacityLowL": 64.3,
    "capacityHighL": 70.7,
    "lidded": false
  },
  {
    "id": "euro-600x400x365",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 365,
    "capacityL": 68.3,
    "capacityLowL": 69.3,
    "capacityHighL": 75.9,
    "lidded": false
  },
  {
    "id": "euro-600x400x400",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 400,
    "capacityL": 75.2,
    "capacityLowL": 76.2,
    "capacityHighL": 83.3,
    "lidded": false
  },
  {
    "id": "euro-600x400x420",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 420,
    "capacityL": 79.1,
    "capacityLowL": 80.2,
    "capacityHighL": 87.5,
    "lidded": false
  },
  {
    "id": "euro-600x400x465",
    "family": "euro",
    "length": 600,
    "width": 400,
    "height": 465,
    "capacityL": 87.9,
    "capacityLowL": 89.1,
    "capacityHighL": 97,
    "lidded": false
  },
  {
    "id": "euro-400x300x120",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 120,
    "capacityL": 9.6,
    "capacityLowL": 10,
    "capacityHighL": 11.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x150",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 150,
    "capacityL": 12.2,
    "capacityLowL": 12.7,
    "capacityHighL": 14.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x170",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 170,
    "capacityL": 14,
    "capacityLowL": 14.5,
    "capacityHighL": 16.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x200",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 200,
    "capacityL": 16.6,
    "capacityLowL": 17.2,
    "capacityHighL": 19.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x220",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 220,
    "capacityL": 18.4,
    "capacityLowL": 19,
    "capacityHighL": 21.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x230",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 230,
    "capacityL": 19.2,
    "capacityLowL": 19.9,
    "capacityHighL": 22.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x240",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 240,
    "capacityL": 20.1,
    "capacityLowL": 20.8,
    "capacityHighL": 23.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x270",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 270,
    "capacityL": 22.8,
    "capacityLowL": 23.5,
    "capacityHighL": 26.5,
    "lidded": false
  },
  {
    "id": "euro-400x300x320",
    "family": "euro",
    "length": 400,
    "width": 300,
    "height": 320,
    "capacityL": 27.1,
    "capacityLowL": 28.1,
    "capacityHighL": 31.5,
    "lidded": false
  },
  {
    "id": "euro-300x200x120",
    "family": "euro",
    "length": 300,
    "width": 200,
    "height": 120,
    "capacityL": 4.6,
    "capacityLowL": 4.6,
    "capacityHighL": 5.3,
    "lidded": false
  },
  {
    "id": "euro-300x200x150",
    "family": "euro",
    "length": 300,
    "width": 200,
    "height": 150,
    "capacityL": 5.8,
    "capacityLowL": 5.8,
    "capacityHighL": 6.7,
    "lidded": false
  },
  {
    "id": "euro-300x200x170",
    "family": "euro",
    "length": 300,
    "width": 200,
    "height": 170,
    "capacityL": 6.7,
    "capacityLowL": 6.7,
    "capacityHighL": 7.6,
    "lidded": false
  },
  {
    "id": "euro-300x200x220",
    "family": "euro",
    "length": 300,
    "width": 200,
    "height": 220,
    "capacityL": 8.7,
    "capacityLowL": 8.7,
    "capacityHighL": 9.9,
    "lidded": false
  },
  {
    "id": "euro-800x600x220",
    "family": "euro",
    "length": 800,
    "width": 600,
    "height": 220,
    "capacityL": 82.5,
    "capacityLowL": 90,
    "capacityHighL": 90,
    "lidded": false
  },
  {
    "id": "euro-800x600x320",
    "family": "euro",
    "length": 800,
    "width": 600,
    "height": 320,
    "capacityL": 123.8,
    "capacityLowL": 133.9,
    "capacityHighL": 133.9,
    "lidded": false
  },
  {
    "id": "euro-800x600x420",
    "family": "euro",
    "length": 800,
    "width": 600,
    "height": 420,
    "capacityL": 165,
    "capacityLowL": 177.8,
    "capacityHighL": 177.8,
    "lidded": false
  }
];
